{"uuid": "9d02ea98-c18b-463f-9a27-4440bc397990", "children": ["8f576d49-8a2c-4a5d-be79-b4e55e17157e"], "befores": [{"name": "Take ScreenShot on failure", "status": "passed", "start": 1700992061885, "stop": 1700992061885}], "afters": [{"name": "Take ScreenShot on failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\python program\\Digital Codes\\test_cases\\conftest.py\", line 117, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1700992061891, "stop": 1700992061891}], "start": 1700992061885, "stop": 1700992061891}