{"uuid": "0a229e75-4b97-48f8-b87d-9a657e7ab6cc", "children": ["759d248a-e873-4232-931c-154b1bd841eb"], "befores": [{"name": "Take ScreenShot on failure", "status": "passed", "start": 1700992073519, "stop": 1700992073519}], "afters": [{"name": "Take ScreenShot on failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\python program\\Digital Codes\\test_cases\\conftest.py\", line 117, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1700992073531, "stop": 1700992073531}], "start": 1700992073519, "stop": 1700992073531}