{"uuid": "14ad5b51-b8b0-42a9-8338-578a528f11bd", "children": ["a8fa8109-bb36-4866-8e2b-02c1afbbe87f"], "befores": [{"name": "Take ScreenShot on failure", "status": "passed", "start": 1700992061669, "stop": 1700992061669}], "afters": [{"name": "Take ScreenShot on failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\python program\\Digital Codes\\test_cases\\conftest.py\", line 117, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1700992061674, "stop": 1700992061674}], "start": 1700992061669, "stop": 1700992061674}