{"uuid": "8108a63c-1ee6-46ce-a3c1-7102e2d7c6c6", "children": ["a78b6357-c27d-4456-84b6-fcd124010384"], "befores": [{"name": "Take ScreenShot on failure", "status": "passed", "start": 1700992073485, "stop": 1700992073485}], "afters": [{"name": "Take ScreenShot on failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\python program\\Digital Codes\\test_cases\\conftest.py\", line 117, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1700992073490, "stop": 1700992073490}], "start": 1700992073485, "stop": 1700992073490}