{"uuid": "b6d34be7-608c-4e9b-bac7-1662defd0df2", "children": ["c08c1aaa-d1aa-4bf2-8e94-68bc312e6ac6"], "befores": [{"name": "Take ScreenShot on failure", "status": "passed", "start": 1700992061764, "stop": 1700992061764}], "afters": [{"name": "Take ScreenShot on failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vrushabh Manatkar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\python program\\Digital Codes\\test_cases\\conftest.py\", line 117, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1700992061774, "stop": 1700992061774}], "start": 1700992061764, "stop": 1700992061774}